//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTicari.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCTicariEntities : DbContext
    {
        public MVCTicariEntities()
            : base("name=MVCTicariEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Cari> Cari { get; set; }
        public virtual DbSet<Departman> Departman { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Gider> Gider { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<SatisHareket> SatisHareket { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<FaturaKalem> FaturaKalem { get; set; }
        public virtual DbSet<UrunDetay> UrunDetay { get; set; }
        public virtual DbSet<Yapilacak> Yapilacak { get; set; }
        public virtual DbSet<KargoTakip> KargoTakip { get; set; }
        public virtual DbSet<KargoDetay> KargoDetay { get; set; }
        public virtual DbSet<Mesaj> Mesaj { get; set; }
    }
}
