//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTicari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisHareket
    {
        public int SatisID { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Adet { get; set; }
        public decimal Fiyat { get; set; }
        public decimal ToplamTutar { get; set; }
        public Nullable<int> Cari { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<int> Urun { get; set; }
    
        public virtual Cari Cari1 { get; set; }
        public virtual Personel Personel1 { get; set; }
        public virtual Urun Urun1 { get; set; }
    }
}
